### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/prolog#86]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-prolog/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

  - `abstract_classes`
  - `callbacks`
  - `conditionals`
  - `events`
  - `equality`
  - `exception_handling`
  - `generics`
  - `inheritance`
  - `interfaces`
  - `loops`
  - `operator_overloading`
  - `pattern_matching`
  - `polymorphism`
  - `recursion`
  - `threading`
  - `type_conversion`
  - `variables`
  - `arrays`
  - `booleans`
  - `classes`
  - `dates`
  - `discriminated_unions`
  - `enumerations`
  - `floating_point_numbers`
  - `graphs`
  - `integers`
  - `lists`
  - `maps`
  - `matrices`
  - `optional_values`
  - `queues`
  - `records`
  - `sequences`
  - `sets`
  - `stacks`
  - `strings`
  - `structs`
  - `time`
  - `trees`
  - `tuples`
  - `algorithms`
  - `bitwise_operations`
  - `concurrency`
  - `cryptography`
  - `domain_specific_languages`
  - `files`
  - `filtering`
  - `games`
  - `globalization`
  - `logic`
  - `math`
  - `memory_management`
  - `networking`
  - `parallelism`
  - `parsing`
  - `pattern_recognition`
  - `performance`
  - `randomness`
  - `refactoring`
  - `regular_expressions`
  - `searching`
  - `security`
  - `sorting`
  - `text_formatting`
  - `transforming`
  - `behavior_driven_development`
  - `functional_programming`
  - `object_oriented_programming`
  - `reactive_programming`
  - `test_driven_development`
</details>

## Exercises with non-standard topics

- [ ] [`satellite`](https://github.com/exercism/prolog/tree/master/exercises/satellite)
  Incorrect topics:
  - [ ] `binary_trees` (perhaps: `trees`)
  - [ ] `tree_traversals`

## Exercises without topics

- [ ] [`hello-world`](https://github.com/exercism/prolog/tree/master/exercises/hello-world)
- [ ] [`queen-attack`](https://github.com/exercism/prolog/tree/master/exercises/queen-attack)
- [ ] [`triangle`](https://github.com/exercism/prolog/tree/master/exercises/triangle)
- [ ] [`isogram`](https://github.com/exercism/prolog/tree/master/exercises/isogram)
- [ ] [`rna-transcription`](https://github.com/exercism/prolog/tree/master/exercises/rna-transcription)
- [ ] [`anagram`](https://github.com/exercism/prolog/tree/master/exercises/anagram)
- [ ] [`dominoes`](https://github.com/exercism/prolog/tree/master/exercises/dominoes)
- [ ] [`spiral-matrix`](https://github.com/exercism/prolog/tree/master/exercises/spiral-matrix)
- [ ] [`nucleotide-count`](https://github.com/exercism/prolog/tree/master/exercises/nucleotide-count)
- [ ] [`hamming`](https://github.com/exercism/prolog/tree/master/exercises/hamming)
- [ ] [`leap`](https://github.com/exercism/prolog/tree/master/exercises/leap)
- [ ] [`space-age`](https://github.com/exercism/prolog/tree/master/exercises/space-age)
- [ ] [`grains`](https://github.com/exercism/prolog/tree/master/exercises/grains)

**Comment by Average-user** [comment]
I agree that `satellite` should have topic `tree` instead of `binary_tree`. And probably `tree_traversals` is too specific of a topic
.

**Comment by Average-user** [comment]
I would suggest to

- [ ] [`hello-world`](https://github.com/exercism/prolog/tree/master/exercises/hello-world) Leave it with no topic
- [ ] [`queen-attack`](https://github.com/exercism/prolog/tree/master/exercises/queen-attack) `pattern-matching` maybe?
- [ ] [`triangle`](https://github.com/exercism/prolog/tree/master/exercises/triangle) `math`
- [ ] [`isogram`](https://github.com/exercism/prolog/tree/master/exercises/isogram) `strings`
- [ ] [`rna-transcription`](https://github.com/exercism/prolog/tree/master/exercises/rna-transcription) `transforming`
- [ ] [`anagram`](https://github.com/exercism/prolog/tree/master/exercises/anagram) `strings`
- [ ] [`dominoes`](https://github.com/exercism/prolog/tree/master/exercises/dominoes) `recursion`
- [ ] [`spiral-matrix`](https://github.com/exercism/prolog/tree/master/exercises/spiral-matrix) `math` `recursion`?
- [ ] [`nucleotide-count`](https://github.com/exercism/prolog/tree/master/exercises/nucleotide-count) `strings`
- [ ] [`hamming`](https://github.com/exercism/prolog/tree/master/exercises/hamming)
`strings` `math`
- [ ] [`leap`](https://github.com/exercism/prolog/tree/master/exercises/leap)
`math`
- [ ] [`space-age`](https://github.com/exercism/prolog/tree/master/exercises/space-age)
`math`
- [ ] [`grains`](https://github.com/exercism/prolog/tree/master/exercises/grains)
`math`

**Comment by ErikSchierboom** [comment]
This isn't relevant anymore due to v3 not using topics.
